// Auto-generated by scripts/fetch-geb.ts — do not edit manually
// Generated: 2026-06-16T00:00:00.000Z
// Source: https://www.geterbrewed.com (custom kit builder)

export interface GebProduct {
  name: string;
  price_gbp: number;
  unit: string;
  category: string;
  in_stock: boolean;
}

export const GEB_INVENTORY: GebProduct[] = [];

export const GEB_LAST_UPDATED = "2026-06-16T00:00:00.000Z";
