// Auto-generated by scripts/fetch-geb.ts — do not edit manually
// Generated: 2026-06-16T00:00:00.000Z
// Source: https://www.geterbrewed.com/custom-grain-kit/

export interface GebProduct {
  name: string;
  price_per_gram_gbp: number;
  unit: "per_gram" | "per_unit";
  category: string;
  stock_status: "in_stock" | "low_stock" | "out_of_stock";
}

export const GEB_INVENTORY: GebProduct[] = [];

export const GEB_LAST_UPDATED = "2026-06-16T00:00:00.000Z";
