// Auto-generated by scripts/fetch-geb.ts — do not edit manually
// Generated: 2026-06-17T10:23:50.659Z
// Source: https://www.geterbrewed.com/custom-grain-kit/

export interface GebProduct {
  name: string;
  price_per_gram_gbp: number;
  unit: "per_gram" | "per_unit";
  category: string;
  stock_status: "in_stock" | "low_stock" | "out_of_stock";
}

export const GEB_INVENTORY: GebProduct[] = [
  {
    "name": "Weyermann® Bohemian Pilsner Malt (EBC 3.0-5.0)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Weyermann® Rye Malt (EBC 4.0-10)",
    "price_per_gram_gbp": 0.0037,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Weyermann® Extra Pale Premium Pilsner Malt (EBC 2.0-2.5)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Eraclea Pilsner Malt (EBC 2.5-4.5)",
    "price_per_gram_gbp": 0.0038,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Barke® Pilsner (EBC 2.5-4.5)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Weyermann® Barke® Vienna (EBC 6.0-9.0)",
    "price_per_gram_gbp": 0.0037,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Dingemans Pale Ale 9 MD Malt (EBC 8.0-10)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Dingemans Pilsen MD Malt (EBC 0.0-3.5)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Wheat Malt MD (EBC 0.0-3.5)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Wheat Malt (EBC 3.0-5.0)",
    "price_per_gram_gbp": 0.0035,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Weyermann® Pale Ale Malt (EBC 3.0-5.0)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Weyermann® Vienna Malt (EBC 6.0-9.0)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Maris Otter MD Malt (EBC max 4.0)",
    "price_per_gram_gbp": 0.0034,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Planet Pale Ale Malt (EBC 4-6)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Craft Pale Ale Malt (EBC 4-6)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Lager Malt (EBC 0-4)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Maris Otter Extra Pale Ale Malt (EBC 0-4)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Maris Otter Pale Ale Malt (EBC 4-6)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Pilsner Malt (EBC 0-3.7)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Super Pale Ale Malt (EBC 0-2)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Planet Extra Pale Ale Malt (EBC 0-4)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Wheat Malt (EBC 0-5)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Finest Pale Ale Golden Promise Malt (EBC 4-6)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Low Colour Golden Promise Malt (EBC 2-4)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Extra Pale Ale Malt (EBC 2.5-3.5)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Best Pale Ale Malt (EBC 4-6)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Rye Malt (EBC 2-6)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Finest Pale Ale Maris Otter Malt (EBC 4-6)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Low Colour Maris Otter Malt (EBC 2-4 )",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Finest Lager Malt (EBC 2-4)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Vienna Malt (EBC 5-10)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Wheat Malt (EBC 2-6)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "MCI Origin Gold Low-Colour Malt (EBC 2-3.5)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "MCI Irish Ale Malt (EBC 4-5)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "MCI Irish Lager Malt (EBC 3-4)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "MCI Irish Stout Malt (EBC 2.5-4)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Barke® Munich (EBC 17-22)",
    "price_per_gram_gbp": 0.0037,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Dingemans Munich 15 MD Malt (EBC 13-16)",
    "price_per_gram_gbp": 0.003,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Munich Malt Type 1 (EBC 12-18)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Muntons Munich Malt (EBC 12-20)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Vienna Malt (EBC 7-12)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Munich Malt (EBC 18-22)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Munich Malt Type 2 (EBC 20-25)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Base Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Muntons Dextrin Malt (EBC 0-7)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Dextrin Malt (EBC 1.3-1.6)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Chit Malt (EBC 2.5-3.5)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Wheat Malt Dark (EBC 15-20)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Dingemans Mroost Wheat Malt 30 MD (EBC 23-35)",
    "price_per_gram_gbp": 0.0033,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Weyermann® Abbey Malt (EBC 40-50)",
    "price_per_gram_gbp": 0.0037,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Dingemans Amber - Aromatic® MD Malt (EBC 40-60)",
    "price_per_gram_gbp": 0.003,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Toasted Rye 40 MD (EBC 30-50)",
    "price_per_gram_gbp": 0.0036,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Amber Malt (EBC 23-46)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Amber Malt (EBC 54-71)",
    "price_per_gram_gbp": 0.0031,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Melanoidin MD (EBC 60-80)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Biscuit 50 MD (EBC 47-70)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Brown Malt (EBC 115-150)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Chocolate Rye 300 MD (EBC 250-350)",
    "price_per_gram_gbp": 0.0037,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Light Chocolate Malt (EBC 205-250)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Pale Chocolate Malt (EBC 450-700)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Brown Malt (EBC 400-508)",
    "price_per_gram_gbp": 0.0031,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Pale Chocolate Malt (EBC 535-669)",
    "price_per_gram_gbp": 0.0031,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Carafa® Special Type 1 Malt (EBC 800-1000)",
    "price_per_gram_gbp": 0.0043,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Carafa® Special Type 2 Malt (EBC 1100-1200)",
    "price_per_gram_gbp": 0.0043,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Roasted Barley (EBC 1000-1300)",
    "price_per_gram_gbp": 0.0041,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Dingemans Chocolate Mroost 900 MD (EBC 800-1000)",
    "price_per_gram_gbp": 0.0033,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Pealed Roasted Barley MD (EBC 1000-1400)",
    "price_per_gram_gbp": 0.0034,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Chocolate Malt (EBC 1020-1250)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Chocolate Malt (EBC 1067-1300)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Roasted Barley Malt (EBC 1300-1900)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Carafa® Special Type 3 Malt (EBC 1300-1500)",
    "price_per_gram_gbp": 0.0043,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Black Mroost 1400 MD (EBC 1300-1500)",
    "price_per_gram_gbp": 0.0033,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Black Malt (EBC 1350 min)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Roasted Barley (EBC 1350-1700)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Black Malt (EBC 1433-1900)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Lightly Kilned Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Acidulated Malt (EBC 2.5-12)",
    "price_per_gram_gbp": 0.0051,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Carapils® Malt (EBC 2.5-6.5)",
    "price_per_gram_gbp": 0.0039,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "GEB - French and Jupps Cara Gold Malt (EBC 10-17)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons CaraGlow Malt (EBC 10-20)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Carahell® Malt (EBC 20-30)",
    "price_per_gram_gbp": 0.0039,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Dingemans Cara 20 MD (EBC 15-27)",
    "price_per_gram_gbp": 0.0031,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Cara Malt (EBC 25-40)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® CaraBelge® Malt (EBC 30-35)",
    "price_per_gram_gbp": 0.004,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Weyermann® CaraRed® Malt (EBC 40-60)",
    "price_per_gram_gbp": 0.004,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Cara 50 MD (EBC 40-60)",
    "price_per_gram_gbp": 0.0031,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Caramalt Malt (EBC 30-42)",
    "price_per_gram_gbp": 0.003,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® CaraAmber® Malt (EBC 60-80)",
    "price_per_gram_gbp": 0.004,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Weyermann® CaraMunich® Type 1 Malt (EBC 80-100)",
    "price_per_gram_gbp": 0.0039,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Melanoidin Malt (EBC 60-80)",
    "price_per_gram_gbp": 0.004,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Dingemans Aroma 100 MD Malt (EBC 90-110)",
    "price_per_gram_gbp": 0.0031,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Karrewheat 77 MD (EBC 70-100)",
    "price_per_gram_gbp": 0.0033,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Aromatic Malt (EBC 50-70)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Premium English Caramalt (EBC 54-66)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® CaraMunich® Type 2 (EBC 110-130)",
    "price_per_gram_gbp": 0.0039,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "low_stock"
  },
  {
    "name": "Weyermann® Caramunich® Type 3 Malt (EBC 140-160)",
    "price_per_gram_gbp": 0.0039,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® CaraRye® Malt (EBC 150-200)",
    "price_per_gram_gbp": 0.0043,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® CaraWheat® Malt (EBC 100-140)",
    "price_per_gram_gbp": 0.0042,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Aroma 150 MD Malt (EBC 125-175)",
    "price_per_gram_gbp": 0.0031,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Cara 120 MD (EBC 100-140)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Cara 200 MD (EBC 180-220)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Light Crystal (EBC 91-115)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Medium Crystal (EBC 125-150)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Standard Crystal (EBC 160-185)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Crystal Medium Malt (EBC 167-190)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Crystal T50 Malt (EBC 126-140)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Crystal Light Malt (EBC 95-113)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Dark Aromatic Malt (EBC 130-150)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Special W® Malt (EBC 280-320)",
    "price_per_gram_gbp": 0.0042,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Dark Crystal (EBC 230-280)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Crystal Dark Malt (EBC 250-285)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Red Rye Crystal Malt (EBC 237-310)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons DRC Malt (EBC 280-320)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® CaraAroma® Malt (EBC 350-450)",
    "price_per_gram_gbp": 0.0042,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Dingemans Special B MD (EBC 270-350)",
    "price_per_gram_gbp": 0.0033,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Dingemans Coffee Mroost 450 MD (EBC 400-500)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB - French and Jupps Extra Dark Crystal (EBC 435-550)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Crystal Extra Dark Malt (EBC 450-500)",
    "price_per_gram_gbp": 0.0029,
    "unit": "per_gram",
    "category": "Caramel & Crystal Malt",
    "stock_status": "in_stock"
  },
  {
    "name": "Rice Hulls (EBC None)",
    "price_per_gram_gbp": 0.0028,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Torrefied Barley",
    "price_per_gram_gbp": 0.0017,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Torrefied Cracked Oats",
    "price_per_gram_gbp": 0.002,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "out_of_stock"
  },
  {
    "name": "GEB Torrefied Wheat",
    "price_per_gram_gbp": 0.0017,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Torrefied Maize",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "Muntons Malted Rye Flakes (EBC 40)",
    "price_per_gram_gbp": 0.003,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Muntons Torrefied Wheat (EBC 0-6)",
    "price_per_gram_gbp": 0.0027,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Malted Oats (EBC 2-4)",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "Simpsons Golden Naked Oats (EBC 12-24)",
    "price_per_gram_gbp": 0.0032,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Flaked Toasted Rye",
    "price_per_gram_gbp": 0.0016,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Flaked Toasted Wheat",
    "price_per_gram_gbp": 0.0015,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Flaked Torrefied Barley",
    "price_per_gram_gbp": 0.0016,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Flaked Toasted Barley",
    "price_per_gram_gbp": 0.0016,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Flaked Torrefied Rice",
    "price_per_gram_gbp": 0.0043,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Standard Rolled Oats",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "out_of_stock"
  },
  {
    "name": "GEB Jumbo Oats",
    "price_per_gram_gbp": 0.0026,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "GEB Flaked Torrefied Wheat",
    "price_per_gram_gbp": 0.0015,
    "unit": "per_gram",
    "category": "Flaked & Unmalted Adjuncts",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Beech Smoked Malt 4-8 EBC (EBC None)",
    "price_per_gram_gbp": 0.0041,
    "unit": "per_gram",
    "category": "Smoked Malts",
    "stock_status": "in_stock"
  },
  {
    "name": "Weyermann® Oak Smoked Wheat Malt 4-6 EBC (EBC None)",
    "price_per_gram_gbp": 0.0043,
    "unit": "per_gram",
    "category": "Smoked Malts",
    "stock_status": "in_stock"
  },
  {
    "name": "Enigma T90 Hop Pellets (Australia) (2024) AA: 19.0%",
    "price_per_gram_gbp": 0.0901,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Vic Secret T90 Hop Pellets (Australia) (2025) AA: 19%",
    "price_per_gram_gbp": 0.089,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Ella T90 Hop Pellets (Australia) (2024) AA: 16.5%",
    "price_per_gram_gbp": 0.0881,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Topaz T90 Hop Pellets (Australia) (2021) AA: 20.2%",
    "price_per_gram_gbp": 0.0876,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Galaxy T90 Hop Pellets (Australia) (2025) AA: 17.2%",
    "price_per_gram_gbp": 0.0916,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Eclipse T90 Hop Pellets (Australia) (2024) AA: 19.7%",
    "price_per_gram_gbp": 0.0969,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Saaz T90 Hop Pellets (Czech) (2025) AA: 4.1%",
    "price_per_gram_gbp": 0.0605,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Tardif de Bourgogne T90 Hop Pellets (France) (2024) AA: 3.8%",
    "price_per_gram_gbp": 0.058,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Petit Blanc T90 Hop Pellets (France) (2024) AA: 3.4%",
    "price_per_gram_gbp": 0.0603,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Mandarina Bavaria T90 Hop Pellets (Germany) (2025) AA: 9.1%",
    "price_per_gram_gbp": 0.0397,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Perle T90 Hop Pellets (Germany) (2024) AA: 7.1%",
    "price_per_gram_gbp": 0.0429,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Hallertau Mittelfruh T90 Hop Pellets (Germany) (2025) AA: 4.0%",
    "price_per_gram_gbp": 0.0546,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Hallertauer Tradition T90 Hop Pellets (Germany) (2024) AA: 5.5%",
    "price_per_gram_gbp": 0.04,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Hallertau Hersbrucker T90 Hop Pellets (Germany) (2025) AA: 4.1%",
    "price_per_gram_gbp": 0.0507,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Hallertauer Magnum T90 Hop Pellets (Germany) (2025) AA: 13.8%",
    "price_per_gram_gbp": 0.0431,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Polaris T90 Hop Pellets (Germany) (2023) AA: 18.4%",
    "price_per_gram_gbp": 0.0464,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Spalter Select T90 Hop Pellets (Germany) (2024) AA: 4.3%",
    "price_per_gram_gbp": 0.05,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Hallertau Blanc T90 Hop Pellets (Germany) (2024) AA: 10.7%",
    "price_per_gram_gbp": 0.0393,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Huell Melon T90 Hop Pellets (Germany) (2024) AA: 5.7%",
    "price_per_gram_gbp": 0.0511,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Northern Brewer T90 Hop Pellets (Germany) (2024) AA: 8.4%",
    "price_per_gram_gbp": 0.0464,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Tettnang T90 Hop Pellets (Germany) (2024) AA: 3.7%",
    "price_per_gram_gbp": 0.066,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Akoya T90 Hop Pellets (Germany) (2022) AA: 8.8%",
    "price_per_gram_gbp": 0.0527,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Solero T90 Hop Pellets (Germany) (2022) AA: 8.4%",
    "price_per_gram_gbp": 0.0534,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Ariana T90 Hop Pellets (Germany) (2023) AA: 9.7%",
    "price_per_gram_gbp": 0.0464,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Tango T90 Hop Pellets (Germany) (2023) AA: 9.0%",
    "price_per_gram_gbp": 0.0592,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Herkules T90 Hop Pellets (Germany) (2024) AA: 18.0%",
    "price_per_gram_gbp": 0.0405,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Saphir T90 Hop Pellets (Germany) (2024) AA: 3.3%",
    "price_per_gram_gbp": 0.0517,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Rottenburger Spat T90 Hop Pellets (Germany) (2022) AA: 1.9%",
    "price_per_gram_gbp": 0.0523,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Diamant T90 Hop Pellets (Germany) (2023) AA: 8.3%",
    "price_per_gram_gbp": 0.0399,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Tettnang Organic T90 Hop Pellets (Germany) (2024) AA: 4.7%",
    "price_per_gram_gbp": 0.0809,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Hallertauer Tradition Organic T90 Hop Pellets (Germany) (2024) AA: 6.0%",
    "price_per_gram_gbp": 0.0743,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Mandarina Bavaria Organic T90 Hop Pellets (Germany) (2023) AA: 9.7%",
    "price_per_gram_gbp": 0.0677,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Hallertau Blanc Organic T90 Hop Pellets (Germany) (2024) AA: 12.2%",
    "price_per_gram_gbp": 0.0721,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Sorachi Ace T90 Hop Pellets (Japan) (2024) AA: 9.2%",
    "price_per_gram_gbp": 0.0845,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Nelson Sauvin T90 Hop Pellets (New Zealand) (2025) AA: 14.1%",
    "price_per_gram_gbp": 0.0729,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Pacifica T90 Hop Pellets (New Zealand) (2023) AA: 3.9%",
    "price_per_gram_gbp": 0.0778,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Rakau T90 Hop Pellets (New Zealand) (2023) AA: 10.7%",
    "price_per_gram_gbp": 0.0743,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Motueka T90 Hop Pellets (New Zealand) (2025) AA: 6.8%",
    "price_per_gram_gbp": 0.0743,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Riwaka T90 Hop Pellets (New Zealand) (2025) AA: 5.1%",
    "price_per_gram_gbp": 0.0729,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Nectaron T90 Hop Pellets (New Zealand) (2025) AA: 13.4%",
    "price_per_gram_gbp": 0.0893,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Pacific Jade T90 Hop (New Zealand) (2021) AA: 10.71%",
    "price_per_gram_gbp": 0.0757,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Southern Cross T90 Hop (New Zealand) (2023) AA: 12.2%",
    "price_per_gram_gbp": 0.0743,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Wai-iti T90 Hop (New Zealand) (2025) AA: 3.9%",
    "price_per_gram_gbp": 0.0783,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Kohatu T90 Hop (New Zealand) (2025) AA: 7.7%",
    "price_per_gram_gbp": 0.0805,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Wakatu T90 Hop (New Zealand) (2022) AA: 5.6%",
    "price_per_gram_gbp": 0.0782,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Superdelic T90 Hop Pellets (New Zealand) (2024) AA: 10.2%",
    "price_per_gram_gbp": 0.107,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Aurora T90 Hop Pellets (Slovenia) (2024) AA: 9.5%",
    "price_per_gram_gbp": 0.0429,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Bobek T90 Hop Pellets (Slovenia) (2023) AA: 5.6%",
    "price_per_gram_gbp": 0.0422,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Styrian Goldings T90 Hop Pellets (Slovenia) (2025) AA: 4.5%",
    "price_per_gram_gbp": 0.0452,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Savinjski Golding T90 Hop Pellets (Slovenia) (2024) AA: 3.8%",
    "price_per_gram_gbp": 0.0475,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Styrian Wolf T90 Hop Pellets (Slovenia) (2023) AA: 12.5%",
    "price_per_gram_gbp": 0.0441,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Styrian Dragon T90 Hop Pellets (Slovenia) (2023) AA: 8.5%",
    "price_per_gram_gbp": 0.0462,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Styrian Fox T90 Hop Pellets (Slovenia) (2021) AA: 8.9%",
    "price_per_gram_gbp": 0.049,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Styrian Cardinal T90 Hop Pellets (Slovenia) (2022) AA: 7.4%",
    "price_per_gram_gbp": 0.0422,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Challenger T90 Hop Pellets (UK) (2025) AA: 8.3%",
    "price_per_gram_gbp": 0.0559,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "East Kent Goldings T90 Hop Pellets (UK) (2025) AA: 6.33%",
    "price_per_gram_gbp": 0.0572,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Fuggles T90 Hop Pellets (UK) (2025) AA: 5.57%",
    "price_per_gram_gbp": 0.0586,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Bramling Cross T90 Hop Pellets (UK) (2025) AA: 7.62%",
    "price_per_gram_gbp": 0.0586,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Pilgrim T90 Hop Pellets (UK) (2025) AA: 9.5%",
    "price_per_gram_gbp": 0.0531,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "First Gold T90 Hop Pellets (UK) (2025) AA: 9.3%",
    "price_per_gram_gbp": 0.0596,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Admiral T90 Hop Pellets (UK) (2025) AA: 14.58%",
    "price_per_gram_gbp": 0.0531,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Target T90 Hop Pellets (UK) (2025) AA: 12.34%",
    "price_per_gram_gbp": 0.0531,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Jester T90 Hop Pellets (UK) (2021) AA: 7.4%",
    "price_per_gram_gbp": 0.056,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Olicana T90 Hop Pellets (UK) (2021) AA: 6.9%",
    "price_per_gram_gbp": 0.056,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Godiva T90 Hop Pellets (UK) (2021) AA: 7.8%",
    "price_per_gram_gbp": 0.0575,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Harlequin T90 Hop Pellets (UK) (2022) AA: 9.6%",
    "price_per_gram_gbp": 0.0763,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Endeavour T90 Hop Pellets (UK) (2025) AA: 8.77%",
    "price_per_gram_gbp": 0.0559,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Ernest T90 Hop Pellets (UK) (2025) AA: 5.7%",
    "price_per_gram_gbp": 0.0559,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Progress T90 Hop Pellets (UK) (2025) AA: 9.5%%",
    "price_per_gram_gbp": 0.0534,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Citra Cryo Hop Pellets (2025) AA: 24.8%",
    "price_per_gram_gbp": 0.1548,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Simcoe Cryo Hop Pellets (2025) AA: 22.0%",
    "price_per_gram_gbp": 0.1496,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Pop Original Blend Cryo Hop Pellets (2025) AA: 23.1%",
    "price_per_gram_gbp": 0.1751,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Amarillo T90 Hop Pellets (USA) (2025) AA: 9.6%",
    "price_per_gram_gbp": 0.0801,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Centennial T90 Hop Pellets (USA) (2025) AA: 9.5%",
    "price_per_gram_gbp": 0.0636,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Citra T90 Hop Pellets (USA) (2025) AA: 13.9%",
    "price_per_gram_gbp": 0.0792,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Chinook T90 Hop Pellets (USA) (2025) AA: 12.5%",
    "price_per_gram_gbp": 0.0647,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Columbus T90 Hop Pellets (USA) (2025) AA: 16.1%",
    "price_per_gram_gbp": 0.058,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "El Dorado T90 Hop Pellets (USA) (2024) AA: 13.5%",
    "price_per_gram_gbp": 0.0687,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Ekuanot T90 Hop Pellets (USA) (2024) AA: 13.3%",
    "price_per_gram_gbp": 0.0681,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Mosaic T90 Hop Pellets (USA) (2025) AA: 13.9%",
    "price_per_gram_gbp": 0.0759,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Simcoe T90 Hop Pellets (USA) (2025) AA: 13.4%",
    "price_per_gram_gbp": 0.078,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Cascade T90 Hop Pellets (USA) (2025) AA: 6.1%",
    "price_per_gram_gbp": 0.0599,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Azacca T90 Hop Pellets (USA) (2023) AA: 11%",
    "price_per_gram_gbp": 0.0891,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Sabro T90 Hop Pellets (USA) (2025) AA: 14.2%",
    "price_per_gram_gbp": 0.0714,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Cashmere T90 Hop Pellets (USA) (2024) AA: 9.3%",
    "price_per_gram_gbp": 0.0743,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Comet T90 Hop Pellets (USA) (2023) AA: 11.3%",
    "price_per_gram_gbp": 0.0592,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Bru-1 T90 Hop Pellets (USA) (2023) AA: 13.4%",
    "price_per_gram_gbp": 0.0828,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Summit T90 Hop Pellets (USA) (2021) AA: 14.5%",
    "price_per_gram_gbp": 0.0585,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Idaho 7 T90 Hop Pellets (USA) (2024) AA: 11.4%",
    "price_per_gram_gbp": 0.07,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Talus T90 Hop Pellets (USA) (2023) AA: 7.9%",
    "price_per_gram_gbp": 0.0746,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Willamette T90 Hop Pellets (USA) (2024) AA: 5.2%",
    "price_per_gram_gbp": 0.0665,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Sultana T90 Hop Pellets (USA) (2022) AA: 13.7%",
    "price_per_gram_gbp": 0.0871,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Strata T90 Hop Pellets (USA) (2025) AA: 13.7%",
    "price_per_gram_gbp": 0.1048,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Lotus T90 Hop Pellets (USA) (2021) AA: 16.1%",
    "price_per_gram_gbp": 0.0762,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Trident T90 Hop Pellets (USA) 2021 (2021) AA: 13.5%",
    "price_per_gram_gbp": 0.0703,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Trident T90 Hop Pellets (USA) 2022 (2022) AA: 12.8%",
    "price_per_gram_gbp": 0.0814,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Lemondrop T90 Hop Pellets (USA) (2022) AA: 4.8%",
    "price_per_gram_gbp": 0.0842,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "Ahtanum T90 Hop Pellets (USA) (2023) AA: 3.7%",
    "price_per_gram_gbp": 0.0641,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "in_stock"
  },
  {
    "name": "Krush™ HBC 586 T90 Hop Pellets (USA) (2024) AA: 13.6%",
    "price_per_gram_gbp": 0.0891,
    "unit": "per_gram",
    "category": "T90 Hops",
    "stock_status": "low_stock"
  },
  {
    "name": "AEB Fermoale AY3 Yeast 11.5g",
    "price_per_gram_gbp": 2.27,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "AEB Fermoale AY4 Yeast 11.5g",
    "price_per_gram_gbp": 2.27,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "AEB Fermolager W Yeast 11.5g",
    "price_per_gram_gbp": 2.58,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "AEB Fermoale New-E Yeast 11.5g​",
    "price_per_gram_gbp": 2.58,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Fermentis SafAle™ K-97 11.5g",
    "price_per_gram_gbp": 2.59,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafLager™ S-189 Yeast 11.5g",
    "price_per_gram_gbp": 4.49,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ F-2 25g",
    "price_per_gram_gbp": 2.34,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ BE-256 11.5g",
    "price_per_gram_gbp": 3.58,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ BE-134 11.5g",
    "price_per_gram_gbp": 3.13,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafLager™ W-34/70 Yeast 11.5g",
    "price_per_gram_gbp": 4.6,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ S-04 11.5g",
    "price_per_gram_gbp": 2.5,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ US-05 Yeast 11.5g",
    "price_per_gram_gbp": 2.66,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ S-33 11.5g",
    "price_per_gram_gbp": 1.95,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ T-58 Yeast 11.5g",
    "price_per_gram_gbp": 1.68,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ WB-06 Yeast 11.5g",
    "price_per_gram_gbp": 3.24,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafLager™ S-23 Yeast 11.5g",
    "price_per_gram_gbp": 3.99,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafCider™ AB-1 (Ex SafCider) 5g",
    "price_per_gram_gbp": 2.07,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafCider™ AS-2 5g",
    "price_per_gram_gbp": 2.32,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafCider™ AC-4 5g",
    "price_per_gram_gbp": 2.27,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafCider™ TF-6 5g",
    "price_per_gram_gbp": 2.17,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafBrew BR-8 Yeast 5g",
    "price_per_gram_gbp": 4.92,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ BW-20 Yeast 11.5g",
    "price_per_gram_gbp": 3.16,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafAle™ W-68 Yeast 11.5g",
    "price_per_gram_gbp": 3.08,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafBrew™ HA-18 Yeast 25g",
    "price_per_gram_gbp": 7.11,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafBrew™ DW-17 25g",
    "price_per_gram_gbp": 6.94,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafBrew™ LD-20 25g",
    "price_per_gram_gbp": 9.16,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafBrew™ DA-16 Yeast 25g",
    "price_per_gram_gbp": 6.94,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Fermentis SafLager™ SH-45 Yeast 11.5g",
    "price_per_gram_gbp": 5.29,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Norsk Kveik K.9 Ebbegarden",
    "price_per_gram_gbp": 6.28,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Norsk Kveik K.22 Stalljen",
    "price_per_gram_gbp": 6.28,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Norsk Kveik K.14 Eitrheim",
    "price_per_gram_gbp": 6.28,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Norsk Kveik K.1 Voss",
    "price_per_gram_gbp": 6.29,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Abbaye™ Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand BRY-97™ American West Coast Ale Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Windsor Ale Dried 11g Yeast",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Wit™ Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand CBC-1™ Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Diamond Lager Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Munich Classic Wheat Beer Yeast 11g",
    "price_per_gram_gbp": 3.53,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand New England Ale Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Kveik Voss Dried Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "WildBrew Philly Sour Lallemand Yeast 11g",
    "price_per_gram_gbp": 3.9,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Verdant IPA Yeast 11g",
    "price_per_gram_gbp": 3.65,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Farmhouse Hybrid Saison-Style Yeast 11g",
    "price_per_gram_gbp": 4.84,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand Nottingham Beer Yeast 11g",
    "price_per_gram_gbp": 4.03,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lallemand NovaLager Yeast 11g",
    "price_per_gram_gbp": 4.45,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Lalbrew Pomona Modern Hybrid IPA yeast 11g",
    "price_per_gram_gbp": 4.54,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M20 Bavarian Wheat Yeast",
    "price_per_gram_gbp": 2.35,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M84 Bohemian Lager Yeast",
    "price_per_gram_gbp": 2.77,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M44 US West Coast Yeast",
    "price_per_gram_gbp": 2.57,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M02 Cider Yeast",
    "price_per_gram_gbp": 1.64,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M76 Bavarian Lager",
    "price_per_gram_gbp": 3.53,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M47 Belgian Abbey",
    "price_per_gram_gbp": 2.35,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M41 Belgian Ale Yeast",
    "price_per_gram_gbp": 2.75,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M31 Belgian Tripel",
    "price_per_gram_gbp": 2.97,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M54 Californian Lager",
    "price_per_gram_gbp": 2.77,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M15 Empire Ale",
    "price_per_gram_gbp": 2.77,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M29 French Saison Ale",
    "price_per_gram_gbp": 3.06,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M05 Mead Yeast",
    "price_per_gram_gbp": 1.42,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M36 Liberty Bell Ale Yeast",
    "price_per_gram_gbp": 2.35,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M42 New World Strong Ale",
    "price_per_gram_gbp": 2.35,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks SN9 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Mangrove Jacks MA33 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks CR51 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M21 Belgian Wit Yeast",
    "price_per_gram_gbp": 2.35,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks CL23 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks R56 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks BV7 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks AW4 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks VR21 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks CY17 Wine Yeast",
    "price_per_gram_gbp": 1.19,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M66 Hophead Ale Yeast",
    "price_per_gram_gbp": 3.08,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M12 Kveik Yeast",
    "price_per_gram_gbp": 3.36,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M24 Versa Lager",
    "price_per_gram_gbp": 2.74,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "LalBrew® House Ale 11g",
    "price_per_gram_gbp": 3.68,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Mangrove Jacks M08 Premium Cider Yeast",
    "price_per_gram_gbp": 2.33,
    "unit": "per_unit",
    "category": "Dried Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "WLE4100-HB Ultra Ferm Home-brew 10ml",
    "price_per_gram_gbp": 2.29,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Yorkshire Square Ale Yeast WLP037 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "WLE4000 - Clarity Ferm Home-brew 10ml - White Labs Yeast",
    "price_per_gram_gbp": 2.67,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs California Ale Yeast WLP001 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Tropicale Yeast Blend WLP077 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Non STA1son Ale Yeast Blend WLP561 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs German X Lager Yeast WLP835 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Belgian Strong Ale Yeast WLP545 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Belgian Saison II Ale Yeast WLP566 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs California IV Ale Yeast WLP019 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Dusseldorf Alt Ale Yeast WLP036 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Sigmund Kveik Ale Yeast WLP520 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Burton Ale Yeast WLP023 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs California V Ale Yeast WLP051 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs American Ale Yeast Blend WLP060 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs London Fog Ale Yeast WLP066 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Coastal Haze Ale Yeast Blend WLP067 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Bavarian Weizen Ale Yeast WLP351 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Belgian Wit Ale Yeast WLP400 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Bastogne Belgian Ale Yeast WLP510 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "White Labs Belgian Golden Ale Yeast WLP570 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Pediococcus damnosus WLP661 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Old Bavarian Lager Yeast WLP920 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Charlie's Fist Bump Yeast WLP1983 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs NA All Day WLP618 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs English Ale Yeast WLP002 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Irish Ale Yeast WLP004 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Bedford British Ale Yeast WLP006 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Dry English Ale Yeast WLP007 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "White Labs East Coast Ale Yeast WLP008 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs London Ale Yeast WLP013 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs German/Kolsch Ale Yeast WLP029 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs San Diego Super Ale Yeast WLP090 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Burlington Ale Yeast WLP095 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Super High Gravity Ale Yeast WLP099 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Hefeweizen Ale Yeast WLP300 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Hefeweizen IV Ale Yeast WLP380 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Monastery Ale Yeast WLP500 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Hornindal Kveik Ale Yeast WLP521 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Abbey Ale Yeast WLP530 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Belgian Saison I Ale Yeast WLP565 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Belgian Style Saison Ale Yeast Blend WLP568 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Torulaspora delbrueckii WLP603 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Saccharomyces brux-like Trois WLP644 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Brettanomyces claussenii WLP645 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Brettanomyces bruxellensis Trois Vrai WLP648 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Brettanomyces bruxellensis WLP650 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Brettanomyces lambicus WLP653 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Belgian Sour Mix 1 WLP655 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Flemish Ale Blend WLP665 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs American Farmhouse Blend WLP670 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Lactobacillus brevis WLP672 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Lactobacillus delbrueckii WLP677 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Lactobacillus plantarum WLP693 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Czech Budejovice Lager Yeast WLP802 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs San Francisco Lager Yeast WLP810 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs German Lager Yeast WLP830 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs German Bock Lager Yeast WLP833 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "White Labs Copenhagen Lager Yeast WLP850 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs High Pressure Lager Yeast WLP925 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Funktown Pale Ale Yeast Blend WLP4027 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Vermont Ale Yeast WLP4000 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Wallonian Farmhouse I Ale Yeast WLP4020 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Wallonian Farmhouse II Ale Yeast WLP4022 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Hessian Pils Lager Yeast WLP4035 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Hazy Daze Yeast Blend I WLP4042 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Hazy Daze Yeast Blend II WLP4044 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Simonaitis Lithuanian Farmhouse Ale Yeast WLP4046 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Lida Kveik Ale Yeast WLP4052 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs British Ale Yeast WLP005 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Edinburgh/Scottish Ale Yeast WLP028 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs American Hefeweizen Ale Yeast WLP320 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Belgian Style Ale Yeast Blend WLP575 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Berliner Weisse Blend WLP630 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Opshaug Kveik Ale Yeast WLP518 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Munich Helles Lager Yeast WLP860 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Fast Lager Yeast WLP845 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Appalachian Tart Yeast WLP631 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Whitbread II Ale Yeast WLP017 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Essex Ale Yeast WLP022 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Premium Bitter Ale Yeast WLP026 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Hansen Ale Yeast Blend WLP075 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Forager Ale Yeast WLP4060 - PurePitch® Next Generation",
    "price_per_gram_gbp": 12.16,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Pilsner Lager Yeast WLP800 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Mexican Lager Yeast WLP940 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "White Labs Maranon Canyon Wild Cacao Yeast WLP546 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Stranda Kveik Ale Yeast WLP519 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Cream Ale Yeast Blend WLP080 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Oktoberfest/Märzen Lager Yeast WLP820 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "White Labs Best Coast Hazy Ale Yeast Blend WLP091 - PurePitch® Next Generation",
    "price_per_gram_gbp": 11.47,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1099 Whitbread Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1187 Ringwood Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1272 All American Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1275 Thames Valley",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1318 London Ale III",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1335 British Ale II",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1450 Denny's Favourite 50 Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1469 West Yorkshire Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1728 Scottish Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2112 California Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2308 Munich Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1388 Belgian Strong Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1762 Belgian Abbey Ale II",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3056 Bavarian Wheat",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3638 Bavarian Wheat",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3763 Roselare",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1007 German Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1332 Northwest Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1028 London Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1056 American Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1010 American Wheat",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 2206 Bavarian Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1214 Belgian Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3522 Belgian Ardennes",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3278 Belgian Lambic Blend",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3724 Belgian Saison",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3944 Belgian Witbier",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2124 Bohemian Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 1098 British Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 2278 Czech Pils",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3711 French Saison",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1084 Irish Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2565 Kolsch",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1968 London ESB Ale",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2007 Pilsen Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "low_stock"
  },
  {
    "name": "Wyeast 3787 Trappist High Gravity",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3068 Weihenstephen Wheat",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 5112 Brettanomyces Bruxellensis",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 5526 Brettanomyces Lambicus",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 5335 Lactobacillus",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 5733 Pediococcus",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1217 West Coast IPA",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 5223-PC Lactobacillus Brevis",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3726 Farmhouse Yeast",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3864 Canadian Belgian Ale Yeast",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2352 Munich Lager II Yeast",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 4134 Sake Yeast",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2575-PC Kolsch Yeast II",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2002-PC Gambrinus Style Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2633 Octoberfest Lager Blend",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 1087-PC Bohemian Ale Blend",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Wyeast 2487-PC Hella Bock Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2247-PC European Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3463 Forbidden Fruit",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 3942 Belgian Wheat",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2000-PC Budvar Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Wyeast 2782-PC Staro Prague Lager",
    "price_per_gram_gbp": 11.89,
    "unit": "per_unit",
    "category": "Liquid Yeast",
    "stock_status": "in_stock"
  },
  {
    "name": "Angelica Root 28g",
    "price_per_gram_gbp": 1.9,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Cardamon Pods 28g",
    "price_per_gram_gbp": 4.93,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Cumin Seeds 28g",
    "price_per_gram_gbp": 1.21,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Juniper Berries 28g",
    "price_per_gram_gbp": 1.75,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Ginger Root chopped 28g",
    "price_per_gram_gbp": 1.38,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Clove 28g",
    "price_per_gram_gbp": 2.85,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Grains of Paradise 28g",
    "price_per_gram_gbp": 4.38,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Coriander Seed 28g",
    "price_per_gram_gbp": 0.62,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Orris Root Powder 28g",
    "price_per_gram_gbp": 2.96,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Sweet Orange Peel Ribbons 28g",
    "price_per_gram_gbp": 1.86,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Lemon Peel Kibbled 28g",
    "price_per_gram_gbp": 2.06,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "low_stock"
  },
  {
    "name": "Bitter orange peel 28g",
    "price_per_gram_gbp": 1.78,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Cassia Bark kibbled 28g",
    "price_per_gram_gbp": 1,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Black Peppercorn 28g",
    "price_per_gram_gbp": 2.06,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Fennel Seed 28g",
    "price_per_gram_gbp": 1.25,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Elderflowers 28g",
    "price_per_gram_gbp": 3.33,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Pink Peppercorns 28g",
    "price_per_gram_gbp": 3.44,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Rose Petals 28g",
    "price_per_gram_gbp": 2.39,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Grapefruit Peel Ribbons 28g",
    "price_per_gram_gbp": 1.98,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Bitter Orange Peel Chopped 28g",
    "price_per_gram_gbp": 1.78,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Sweet Orange Peel Chopped 28g",
    "price_per_gram_gbp": 1.72,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Caraway seeds 28g",
    "price_per_gram_gbp": 0.79,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Still Spirits French Oak Medium Toast Carboy Spiral",
    "price_per_gram_gbp": 14.11,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "low_stock"
  },
  {
    "name": "Still Spirits American Oak Carboy Spiral Medium Toast",
    "price_per_gram_gbp": 10.23,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Still Spirits American Charred Oak Carboy Spiral",
    "price_per_gram_gbp": 10.23,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Hibiscus Flowers - 28g",
    "price_per_gram_gbp": 2.2,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Hawthorn Berries - 28g",
    "price_per_gram_gbp": 3.37,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Elderberries - 28g",
    "price_per_gram_gbp": 2.01,
    "unit": "per_unit",
    "category": "Flavours",
    "stock_status": "in_stock"
  },
  {
    "name": "Candy Sugar Brown Crushed 500g",
    "price_per_gram_gbp": 3.12,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Glycerine Liquid 100ml",
    "price_per_gram_gbp": 2.71,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Mangrove Jacks Carbonation Drops",
    "price_per_gram_gbp": 3.19,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Lactose 500g",
    "price_per_gram_gbp": 3.29,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Brewferm Carbonation Drops for 33 cl - 60 pcs",
    "price_per_gram_gbp": 3.8,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Brewferm Carbonation Drops for 50 cl - 40 pcs",
    "price_per_gram_gbp": 4.83,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Candy Sugar White Crushed 500g",
    "price_per_gram_gbp": 3.12,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Brew Enhancer 1Kg",
    "price_per_gram_gbp": 3.12,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Brew Enhancer 1 - (60% Dextrose, 40% Maltodextrin) 1KG",
    "price_per_gram_gbp": 3.12,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Brew Enhancer 2 - (50% Dextrose, 25% Maltodextrin, 25% Spraymalt) 1KG",
    "price_per_gram_gbp": 5.63,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Priming Sugar 1kg",
    "price_per_gram_gbp": 2.8,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Brewing Sugar 1kg",
    "price_per_gram_gbp": 2.8,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Sorbitol Liquid Sugar 70% 250ml",
    "price_per_gram_gbp": 3.26,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "low_stock"
  },
  {
    "name": "Maltodextrin 1Kg",
    "price_per_gram_gbp": 3.33,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "in_stock"
  },
  {
    "name": "Brewferm Candy Syrup Dark 1L",
    "price_per_gram_gbp": 9.71,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Molasses Sugar",
    "price_per_gram_gbp": 3.51,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "out_of_stock"
  },
  {
    "name": "Candy syrup liquid mild 1L",
    "price_per_gram_gbp": 12.08,
    "unit": "per_gram",
    "category": "Sugars",
    "stock_status": "out_of_stock"
  }
];

export const GEB_LAST_UPDATED = "2026-06-17T10:23:50.664Z";
